Online_Banking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^home/', include('home.urls')),
    re_path(r'^sign_in/', include('sign_in.urls')),
    re_path(r'^blockchain/', include('blockchain.urls')),
]

home/urls.py
from django.urls import include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

app_name = 'home'
urlpatterns = [
    re_path(r'^', views.index, name='index'),
    #re_path(r'^$', views.index, name='index'),

]

urlpatterns += staticfiles_urlpatterns()

sign_in/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import ListView, DetailView
from sign_in.models import LoginValue
app_name = 'sign_in'
urlpatterns = [
    re_path(r'^sign_up/', views.index_sign_up, name='index_sign_up'),
    re_path(r'^forgot_pass/', views.forgot_pass, name='forgot_pass'),
    path('new_user/', views.add_user, name='add_user'),
    path('recovery/', views.recovery_code, name='recovery_code'),
    path('new_pass/', views.new_pass, name='new_pass'),
    path('login_user/', views.login_user, name='login_user'),
    path('personal_cabinet/', views.personal_cabinet, name='personal_cabinet'),
    path('log_out/', views.logout1, name='log_out'),
    path('transfers/', views.transfers, name='transfers'),
    path('change_pass/', views.change_pass_index, name='change_pass_index'),
    path('change_pass1/', views.change_pass, name='change_pass'),
    path('payments/', views.payments, name='payments'),
]

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from sign_in.models import LoginValue
from django.http import HttpResponse
from sign_in.models import Cards


def index(request):
    return render(request, 'home/homePage.html')

home/templates/home/general_view.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static "apple-touch-icon.png" %}">

    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <!--        <link rel="stylesheet" href="assets/css/bootstrap-theme.min.css">-->

    <!--For Plugins external css-->
    <link rel="stylesheet" href="{% static "assets/css/plugins.css" %}"/>
    <link rel="stylesheet" href="{% static "assets/css/lato-webfont.css" %}"/>
    <link rel="stylesheet" href="{% static "assets/css/magnific-popup.css" %}">

    <!--Theme custom css -->
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">

    <!--Theme Responsive css-->
    <link rel="stylesheet" href="{% static "assets/css/responsive.css" %}"/>
    <script src="{% static "assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js" %}"></script>


    <link rel="icon" type="image/png" href="{% static "assets/images/favicon.ico" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">


    <link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3..."/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://bootstraptema.ru/snippets/form/2017/styles.css" rel="stylesheet">
</head>

<body>

<div class='preloader'>
    <div class='loaded'>&nbsp;</div>
</div>

<nav class="navbar navbar-default navbar-fixed-top ">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
                <li class="active"><a href="#home">Home</a></li>
                <li><a href="#transfers">TRANSFERS</a></li>
                <li><a href="#payments">PAYMENTS</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right" class="nav-link dropdown-toggle" href="#" id="navbarDropdown">

                <li class="dropdown on hover">
                    {% if 'sign_in:is_authenticate' %}
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" target="_blank">
                            <button type="button" class="btn btn-secondary dropdown-toggle"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                LOG OUT
                            </button>

                            <span class="caret">
                            </span>
                        </a>
                        <ul class="dropdown-menu" class="hidden">
                            <div class="limiter">
                                <button type="button" class="btn btn-secondary dropdown-toggle"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <a href="personal_cabinet/" target="_blank">
                                        Personal cabinet
                                    </a>
                                </button>
                                <a  href="log_out/" target="_blank">
                                    <button type="button" class="btn btn-secondary dropdown-toggle"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" action="{% url 'sign_in:log_out' %}">
                                        Log out
                                    </button>
                                </a>
                            </div>
                        </ul>

                    {% else %}
                        <a class="dropdown-toggle" data-toggle="dropdown">login<span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" class="hidden">

                            <div class="limiter">
                                <div class="container-login100">
                                    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
                                        <form class="login100-form validate-form"
                                              action="{% url 'sign_in:login_user' %}"
                                              method="post">
                                            {% csrf_token %}
                                            <span class="login100-form-title p-b-33">
		                            				Account Login
                                            </span>

                                            <div class="wrap-input100 validate-input"
                                                 data-validate="Valid Login is required">
                                                <input class="input100" type="text" name="login" placeholder="Login">
                                                <span class="focus-input100-1"></span>
                                                <span class="focus-input100-2"></span>
                                            </div>

                                            <div class="wrap-input100 rs1 validate-input"
                                                 data-validate="Password is required">
                                                <input class="input100" type="password" name="pass"
                                                       placeholder="Password">
                                                <span class="focus-input100-1"></span>
                                                <span class="focus-input100-2"></span>
                                            </div>

                                            <div class="container-login100-form-btn m-t-20">
                                                <button class="login100-form-btn"
                                                        action="{% url 'sign_in:login_user' %}">
                                                    Sign in
                                                </button>
                                            </div>

                                            <div class="text-center p-t-45 p-b-4">
		                            				<span class="txt1">
		                            					Forgot
		                            				</span>

                                                <a href="/sign_in/forgot_pass/" class="txt2 hov1">
                                                    Password?
                                                </a>
                                            </div>

                                            <div class="text-center">
		                            				<span class="txt1">
		                            					Create an account?
		                            				</span>

                                                <a href="/sign_in/sign_up" class="txt2 hov1">
                                                    Sign up
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </ul>
                    {% endif %}
                    <!-- <li><a href="/sign_in/">SIGN IN</a></li> -->

                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>




<script src="{% static "assets/js/vendor/jquery-1.11.2.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.min.js" %}"></script>
<script src="{% static "assets/js/gmaps.min.js" %}"></script>
<script src="{% static "assets/js/jquery.magnific-popup.js" %}"></script>
<script src="{% static "assets/js/plugins.js" %}"></script>
<script src="{% static "assets/js/main.js" %}"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.m.."></script>
<script src="https://bootstraptema.ru/snippets/form/2017/jquery.payform.mi.."></script>
<script src="https://bootstraptema.ru/snippets/form/2017/script.js"></script>


<script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<script src="{% static "vendor/select2/select2.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
<script src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
</body>
</html>