Online_Banking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^home/', include('home.urls')),
    re_path(r'^sign_in/', include('sign_in.urls')),
    re_path(r'^blockchain/', include('blockchain.urls')),
]

home/urls.py
from django.urls import include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

app_name = 'home'
urlpatterns = [
    re_path(r'^', views.index, name='index'),
    #re_path(r'^$', views.index, name='index'),

]

urlpatterns += staticfiles_urlpatterns()

sign_in/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import ListView, DetailView
from sign_in.models import LoginValue
app_name = 'sign_in'
urlpatterns = [
    re_path(r'^sign_up/', views.index_sign_up, name='index_sign_up'),
    re_path(r'^forgot_pass/', views.forgot_pass, name='forgot_pass'),
    path('new_user/', views.add_user, name='add_user'),
    path('recovery/', views.recovery_code, name='recovery_code'),
    path('new_pass/', views.new_pass, name='new_pass'),
    path('login_user/', views.login_user, name='login_user'),
    path('personal_cabinet/', views.personal_cabinet, name='personal_cabinet'),
    path('log_out/', views.logout1, name='log_out'),
    path('transfers/', views.transfers, name='transfers'),
    path('change_pass/', views.change_pass_index, name='change_pass_index'),
    path('change_pass1/', views.change_pass, name='change_pass'),
    path('payments/', views.payments, name='payments'),
]

sign_in/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class Cards(models.Model):
    login = models.CharField(max_length=30)
    number = models.CharField(max_length=30, null=True, blank=True)
    name = models.CharField(max_length=16, null=True, blank=True)
    surname = models.CharField(max_length=16, null=True, blank=True)
    balance = models.CharField(max_length=1000, null=True, blank=True)
    date = models.DateField(max_length=16, null=True, blank=True)
    cvv  = models.CharField(max_length=3, blank=True)


class MyUserManager(BaseUserManager):
    use_in_migrations = True

    # python manage.py createsuperuser
    def create_superuser(self, login, is_staff, password):
        user = self.model(
            login=login,
            is_staff=is_staff,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


class LoginValue(AbstractBaseUser):
    sys_id = models.AutoField(primary_key=True, blank=True)
    login = models.CharField(max_length=127, unique=True, null=False, blank=False)
    phone_number = models.CharField(max_length=11, unique=True, null=False, blank=False, default='')
    iin = models.CharField(max_length=12, unique=True, null=False, blank=False, default='')
    name = models.CharField(max_length=30, null=False, blank=False, default='')
    surname = models.CharField(max_length=30, null=False, blank=False, default='')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "login"
    # REQUIRED_FIELDS must contain all required fields on your User model,
    # but should not contain the USERNAME_FIELD or password as these fields will always be prompted for.
    REQUIRED_FIELDS = ['is_staff', 'iin', 'phone_number', ]

    class Meta:
        app_label = "sign_in"
        db_table = "user_data"

    def __str__(self):
        return self.login

    def get_full_name(self):
        str = self.name + self.surname
        return str

    def get_short_name(self):

        return self.login

    def __str__(self):
        return self.iin

sign_in/forms.py
from django.forms import ModelForm
from sign_in.models import LoginValue
from django import forms

"""

class RegisterForm(ModelForm):
    class Meta:
        model = LoginValue
        fields = ['login', 'phone_number', 'iin', 'name', 'surname', 'password', 'password1']
"""


class RegisterForm(forms.Form):
    login = forms.CharField(max_length=127)
    phone = forms.CharField(min_length=11, max_length=11)
    iin = forms.CharField(min_length=12, max_length=12)
    name = forms.CharField(max_length=30)
    surname = forms.CharField(max_length=30)
    pass1 = forms.CharField(min_length=8)
    pass2 = forms.CharField(min_length=8)

sign_in/views.py
import logging
import urllib
from random import randint
from django.contrib.auth.models import AnonymousUser, User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from sign_in.forms import RegisterForm
from sign_in.models import LoginValue, Cards
from django.contrib import messages


def index_sign_up(request):
    return render(request, 'sign_in/sign_up_page.html')


def forgot_pass(request):
    return render(request, 'sign_in/forgot_pass_page.html')


def personal_cabinet(request):
    return render(request, 'sign_in/personal_cabinet.html')


def change_pass_index(request):
    return render(request, 'sign_in/change_pass.html')


def recovery_code(request):
    all_users = LoginValue.objects.all()
    random_code = str(randint(100000, 999999))
    phone = ''
    if request.method == 'POST':
        phone = request.POST.get('phone')

    temp = 0
    for i in all_users:
        if i.phone_number == phone:
            temp = 1
    if temp == 1:
        mobizon = 'https://api.mobizon.kz/service/message/sendsmsmessage?recipient=' + phone + '&from&text=Your+recovery+code+is+' + random_code + '&apiKey=kz8e497f591b5d08f4a21f78bb8791f60e62118479e62d3954e7c6c2613efa3ca96d67'
        mobizon_link = mobizon
        urllib.request.urlopen(mobizon_link)
        f = open('recovery_data.txt', 'w')
        f.write(random_code + '\n' + phone)
        f.close()
        return render(request, 'sign_in/new_password.html')

    else:
        if phone[0] != '7' and phone[1] != 7 and len(phone) != 11:
            return HttpResponse(phone + "  Incorrect format")
        else:
            return HttpResponse(phone + "  This phone has not registered")


def new_pass(request):
    all_users = LoginValue.objects.all()
    r_code = ''
    pass1 = ''
    pass2 = ''
    f = open('C://Users//Fedor//Desktop//Programming//Python_Projects//Online_Banking//recovery_data.txt', 'r')
    ls = [line.strip() for line in f]
    f.close()
    random_code = ls[0]
    phone = ls[1]
    print(ls[0], ls[1])
    f = open('C://Users//Fedor//Desktop//Programming//Python_Projects//Online_Banking//recovery_data.txt', 'w')
    f.write(' ')
    f.close()
    if request.method == 'POST':
        r_code = request.POST.get('r_code')
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')
    if r_code == random_code:
        if pass1 == pass2:
            for i in all_users:
                if i.phone_number == phone:
                    i.set_password(pass1)
                    i.save()
                    return render(request, 'home/homePage.html')
        else:
            return HttpResponse("Passwords have no equals")
    else:
        return HttpResponse("Recovery code is wrong")


def transfers(request):
    all_cards = Cards.objects.all()
    a = request.session.get('user_id')
    user = LoginValue.objects.get(sys_id=a)
    a1 = {'user': user}
    for i in all_cards:
        if i.login == user.login:
            a1.update({'card': i})
    if request.method == 'POST':
        name = request.POST.get('owner_name')
        name_owner = request.POST.get('owner')
        cvv = request.POST.get('cvv')
        cardNumber = request.POST.get('cardNumber')
        toTrans = request.POST.get('card_number_to_trans')
        money = int(request.POST.get('amount_of_money'))
    i, n, b = 0, 0, 0
    f = open('text.txt', 'w')
    while i < len(all_cards):
        if all_cards[i].number == cardNumber:
            if all_cards[i].cvv == cvv:
                if all_cards[i].name == name:
                    n = i
                    break
        i = i + 1
    i = 0
    while i < len(all_cards):
        if all_cards[i].number == toTrans:
            if all_cards[i].name == name_owner:
                b = i
                break
        i = i + 1
    i = 0
    all_cards[b].balance = int(all_cards[b].balance) + money
    all_cards[n].balance = int(all_cards[n].balance) - money
    all_cards[b].save()
    all_cards[n].save()
    return render(request, 'home/homePage.html', context=a1)


def add_user(request):
    all_users = LoginValue.objects.all()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            login1 = form.cleaned_data.get('login')
            phone1 = form.cleaned_data.get('phone')
            iin = form.cleaned_data.get('iin')
            name = form.cleaned_data.get('name')
            surname = form.cleaned_data.get('surname')
            pass1 = form.cleaned_data.get('pass1')
            pass2 = form.cleaned_data.get('pass2')
            if pass1 == pass2:
                temp = 0
                for i in all_users:
                    if i.login == login1:
                        temp = 1
                    if i.phone_number == phone1:
                        temp = 2
                if temp == 0:
                    new_user = LoginValue.objects.create(login=login1,
                                                         phone_number=phone1,
                                                         iin=iin,
                                                         name=name,
                                                         surname=surname,
                                                         is_staff=False,
                                                         is_active=False)
                    new_user.set_password(pass1)
                    new_user.save()
                    return render(request, 'home/homePage.html')
                elif temp == 2:
                    return HttpResponse("This phone has been already used")
                else:
                    return HttpResponse("This login has been already used")
            else:
                return HttpResponse("Password is not similar")
        else:
            return HttpResponse("Yor data is incorrect")


def login_user(request):
    all_users = LoginValue.objects.all()
    all_cards = Cards.objects.all()
    controller = 0
    a1 = {}
    if request.method == 'POST':
        login1 = request.POST.get('login1')
        pass1 = request.POST.get('pass1')
        lenth = len(all_users)
        for i in range(lenth):
            if all_users[i].login == login1 and all_users[i].check_password(pass1):
                # keys = request.session.keys()
                #                 # print(keys)
                #                 # if str(all_users[i].sys_id) in keys:
                #                 # print("vrode robit")
                #                 # return HttpResponse("This user already auth")
                #                 # else:
                a1 = {'user': all_users[i]}
                all_users[i].is_active = True
                all_users[i].save()
                controller = 1

                request.session['user_id'] = all_users[i].sys_id
                request.session.set_expiry(300)
                print(request.session)

                for i in all_cards:
                    if i.login == login1:
                        a1.update({'card': i})
    if controller == 1:
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            return render(request, 'home/homePage.html', context=a1)
        request.session.set_test_cookie()
        return render(request, 'home/homePage.html', context=a1)
    else:
        return HttpResponse('Your login or password is incorrect')


def logout1(request):
    try:
        request.session.flush()
        request.user = AnonymousUser()
    except KeyError:
        pass
    return HttpResponseRedirect('home/homePage.html')


def payments(request):
    all_cards = Cards.objects.all()
    a = request.session.get('user_id')
    user = LoginValue.objects.get(sys_id=a)
    a1 = {'user': user}
    for i in all_cards:
        if i.login == user.login:
            a1.update({'card': i})
    if request.method == 'POST':
        cardNumber = request.POST.get('cardNumber')
        money = int(request.POST.get('amount_of_money'))
    i, n, b = 0, 0, 0

    f = open('amount.txt', 'w')
    while i < len(all_cards):
        if all_cards[i].number == cardNumber:
            n = i
            # f.write(str(n))
            break
        i = i + 1
    i = 0

    all_cards[b].balance = int(all_cards[b].balance) + money
    all_cards[n].balance = int(all_cards[n].balance) - money
    all_cards[b].save()
    all_cards[n].save()
    return render(request, 'home/homePage.html', context=a1)


def get_user(request, user_id):
    try:
        user = LoginValue.objects.get(sys_id=user_id)
        if user.is_active:
            return user
        return None
    except LoginValue.DoesNotExist:
        logging.getLogger("error_logger").error("user with %(user_id)d not found")
        return None


def change_pass(request):
    all_users = LoginValue.objects.all()
    a = request.session.get('user_id')
    user = LoginValue.objects.get(sys_id=a)
    a1 = {'user': user}
    pass1 = ''
    pass2 = ''
    if request.method == 'POST':
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')
    if pass1 == pass2:
        for i in all_users:
            if i.login == user.login:
                i.set_password(pass1)
                i.save()
        # for i in all_users:
        # i.save()
        return HttpResponseRedirect('home/homePage.html')
    else:
        return HttpResponse("Passwords have no equals")

sign_in/templates/sign_in/change_pass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V19</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!--for sign_in-->
    <link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <!--for sign_in-->

</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
            <form class="login100-form validate-form" action="{% url 'sign_in:change_pass' %}" method="post">
                {% csrf_token %}
                <span class="login100-form-title p-b-33">
                        Please enter new password
                </span>
                <div class="wrap-input100 rs1 validate-input" data-validate="Password is required" id="id_password1">
                    <input class="input100" name="pass1" type="password" placeholder="New password">
                    <span class="focus-input100-1"></span>
                    <span class="focus-input100-2"></span>
                </div>
                <div class="wrap-input100 rs1 validate-input" data-validate="Password is required" id="id_password1">
                    <input class="input100" name="pass2" type="password" placeholder="Repeat password">
                    <span class="focus-input100-1"></span>
                    <span class="focus-input100-2"></span>
                </div>
                <div class="container-login100-form-btn m-t-20">
                    <button class="login100-form-btn" action="{% url 'sign_in:change_pass' %}">
                        Confirm new password
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--for sign_in-->
<script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></div>
    <script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
    <
    script;
    src = "{% static "vendor/bootstrap/js/popper.js" %}" ></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<script src="{% static "vendor/select2/select2.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
<script src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
<!--for sign_in-->

</body>
</html>

sign_in/templates/sign_in/forgot_pass_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V19</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
      <!--for sign_in-->
        <link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}" />
        <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "css/util.css"%}">
	    <link rel="stylesheet" type="text/css" href="{% static "css/main.css"%}">
        <!--for sign_in-->

    </head>
<body>
<div class="limiter">
		<div class="container-login100" >
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form class="login100-form validate-form" action="{% url 'sign_in:recovery_code' %}" method="post">
                     {% csrf_token %}
					<span class="login100-form-title p-b-33">
                        Password recovery
					</span>

					<div class="wrap-input100 rs1 validate-input" data-validate="Phone is required" >
						<input class="input100" type="phone" name="phone" placeholder="Phone without [+] like: (77XX-XXX-XX-XX)">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn" action="{% url 'sign_in:recovery_code' %}">
							Send recovery code
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


 <!--for sign_in-->
    <script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></div>
	<script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
	<script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
	<script src="{% static "vendor/select2/select2.min.js" %}"></script>
	<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
	<script src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
	<script src="{% static "js/main.js"%}" ></script>
        <!--for sign_in-->

</body>
</html>

sign_in/templates/sign_in/new_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V19</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!--for sign_in-->
    <link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css" %}">

    <link rel="stylesheet" type="text/css" href="{% static "css/util.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    <!--for sign_in-->

</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
            <form class="login100-form validate-form" action="{% url 'sign_in:new_pass' %}", method="post">
                {% csrf_token %}
                <span class="login100-form-title p-b-33">
                        Please enter new password
					</span>
                <div class="wrap-input100 rs1 validate-input" data-validate="Password is required" id="id_password1">
                    <input class="input100" name="r_code" placeholder="Recovery code">
                    <span class="focus-input100-1"></span>
                    <span class="focus-input100-2"></span>
                </div>
                <div class="wrap-input100 rs1 validate-input" data-validate="Password is required" id="id_password1">
                    <input class="input100" name="pass1" type="password" placeholder="New password">
                    <span class="focus-input100-1"></span>
                    <span class="focus-input100-2"></span>
                </div>
                <div class="wrap-input100 rs1 validate-input" data-validate="Password is required" id="id_password1">
                    <input class="input100" name="pass2" type="password" placeholder="Repeat password">
                    <span class="focus-input100-1"></span>
                    <span class="focus-input100-2"></span>
                </div>
                <div class="container-login100-form-btn m-t-20">
                    <button class="login100-form-btn" action="{% url 'sign_in:new_pass' %}">
                        Confirm new password
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--for sign_in-->
<script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></div>
    <script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
    <
    script;
    src = "{% static "vendor/bootstrap/js/popper.js" %}" ></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<script src="{% static "vendor/select2/select2.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
<script src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>
<!--for sign_in-->

</body>
</html>

sign_in/templates/sign_in/transfer_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V19</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
      <!--for sign_in-->
        <link rel="icon" type="image/png" href="{% static "images/icons/favicon.ico" %}" />
        <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/css/bootstrap.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/animate/animate.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/css-hamburgers/hamburgers.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/animsition/css/animsition.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/select2/select2.min.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "vendor/daterangepicker/daterangepicker.css"%}">

	    <link rel="stylesheet" type="text/css" href="{% static "css/util.css"%}">
	    <link rel="stylesheet" type="text/css" href="{% static "css/main.css"%}">
        <!--for sign_in-->

    </head>
<body>
<div class="limiter">
		<div class="container-login100" >
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<form action="{% url 'sign_in:transfers_confirm' %}" method="post">
                     {% csrf_token %}
					<span class="login100-form-title p-b-33">
                        Password recovery
					</span>

					<div class="wrap-input100 rs1 validate-input" data-validate="Phone is required" >
						<input class="input100" type="phone" name="phone" placeholder="Phone without [+] like: (77XX-XXX-XX-XX)">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn" action="{% url 'sign_in:transfers_confirm' %}">
							Send recovery code
						</button>
					</div>

				</form>
			</div>
		</div>
	</div>


 <!--for sign_in-->
    <script src="{% static "vendor/jquery/jquery-3.2.1.min.js" %}"></div>
	<script src="{% static "vendor/animsition/js/animsition.min.js" %}"></script>
	<script src="{% static "vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "vendor/bootstrap/js/bootstrap.min.js" %}"></script>
	<script src="{% static "vendor/select2/select2.min.js" %}"></script>
	<script src="{% static "vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "vendor/daterangepicker/daterangepicker.js" %}"></script>
	<script src="{% static "vendor/countdowntime/countdowntime.js" %}"></script>
	<script src="{% static "js/main.js"%}" ></script>
        <!--for sign_in-->

</body>
</html>